# Generated by Django 5.1.2 on 2024-11-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('passward', models.CharField(max_length=12)),
            ],
        ),
    ]
