# Generated by Django 5.1.2 on 2024-11-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='sal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
