# Generated by Django 5.1.2 on 2024-11-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersData',
            new_name='Users',
        ),
    ]
